apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-1
spec:
  replicas: 2
  selector:
    matchExpressions:
      - { key: type, operator: In, values: [web] }
      - { key: ver, operator: Exists }
  template:
    metadata:
      name: pod-1
      labels:
        type: web
        ver: v2
    spec:
      containers:
        - name: container
          image: tmkube/app:v1
      terminationGracePeriodSeconds: 0
