apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  namespace: nm-5
spec:
  containers:
    - name: container
      image: tmkube/app
      resources:
        requests:
          memory: 0.2Gi
        limits:
          memory: 0.4Gi
