apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  selector:
    matchLabels:
      type: app
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        type: app
    spec:
      containers:
        - name: node
          image: ghcr.io/seungh0/k8s-study
