apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-1
spec:
  selector:
    matchLabels:
      type: app
  replicas: 2
  strategy:
    type: Recreate
  revisionHistoryLimit: 1 # 기존 버전의 레플리카셋을 1개로 남김 (기본은 10개임)
  template:
    metadata:
      labels:
        type: app
    spec:
      containers:
        - name: container
          image: tmkube/app:v1
# kubectl rollout history deployment deployment-1
# kubectl rollout undo deployment deployment-1 --to-revision=4
